version: 2

builds:
  - id: otel-distro-builder
    binary: otel-distro-builder-github-action
    main: ./cmd/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

nfpms:
  - id: default
    package_name: otel-distro-builder-github-action
    maintainer: "ObservIQ <support@observiq.com>"
    homepage: "https://github.com/observiq/otel-distro-builder"
    license: "Apache 2.0"
    
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    
    contents:
      - src: ./
        dst: /opt/otel-distro/
        type: dir
        file_info:
          owner: root
          group: root  
          mode: 0755
    
    formats:
      - deb
      - rpm
      - apk

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip